export enum CountryTypeValues  {
    NotSelected = "0",
    Andorra = "1",
    UnitedArabEmirates = "2",
    Afghanistan = "3",
    AntiguaBarbuda = "4",
    Anguilla = "5",
    Albania = "6",
    Armenia = "7",
    NetherlandsAntilles = "8",
    Angola = "9",
    Antarctica = "10",
    Argentina = "11",
    AmericanSamoa = "12",
    Austria = "13",
    Australia = "14",
    Aruba = "15",
    AlandIslands = "16",
    Azerbaijan = "17",
    BosniaHerzegovina = "18",
    Barbados = "19",
    Bangladesh = "20",
    Belgium = "21",
    BurkinaFaso = "22",
    Bulgaria = "23",
    Bahrain = "24",
    Burundi = "25",
    Benin = "26",
    SaintBarthelemy = "27",
    Bermuda = "28",
    Brunei = "29",
    Bolivia = "30",
    BonaireEustatiusSaba  = "31",
    Brazil = "32",
    Bahamas = "33",
    Bhutan = "34",
    BouvetIsland = "35",
    Botswana = "36",
    Belarus = "37",
    Belize = "38",
    Canada = "39",
    CocosIslands = "40",
    DemocraticRepublicCongo = "41",
    CentralAfricanRepublic = "42",
    RepublicCongo = "43",
    Switzerland = "44",
    IvoryCoast = "45",
    CookIslands = "46",
    Chile = "47",
    Cameroon = "48",
    China = "49",
    Colombia = "50",
    CostaRica = "51",
    SerbiaMontenegro = "52",
    Cuba = "53",
    CaboVerde = "54",
    Curacao = "55",
    ChristmasIsland = "56",
    Cyprus = "57",
    Czechia = "58",
    Germany = "59",
    Djibouti = "60",
    Denmark = "61",
    Dominica = "62",
    DominicanRepublic = "63",
    Algeria = "64",
    Ecuador = "65",
    Estonia = "66",
    Egypt = "67",
    WesternSahara = "68",
    Eritrea = "69",
    Spain = "70",
    Ethiopia = "71",
    Finland = "72",
    Fiji = "73",
    FalklandIslands = "74",
    Micronesia = "75",
    FaroeIslands = "76",
    France = "77",
    Gabon = "78",
    UnitedKingdom = "79",
    Grenada = "80",
    Georgia = "81",
    FrenchGuiana = "82",
    Guernsey = "83",
    Ghana = "84",
    Gibraltar = "85",
    Greenland = "86",
    Gambia = "87",
    Guinea = "88",
    Guadeloupe = "89",
    EquatorialGuinea = "90",
    Greece = "91",
    SandwichIslands = "92",
    Guatemala = "93",
    Guam = "94",
    GuineaBissau = "95",
    Guyana = "96",
    HongKong = "97",
    HeardIsland = "98",
    Honduras = "99",
    Croatia = "100",
    Haiti = "101",
    Hungary = "102",
    Indonesia = "103",
    Ireland = "104",
    Israel = "105",
    IsleMan = "106",
    India = "107",
    BritishIndianOceanTerritory = "108",
    Iraq = "109",
    Iran = "110",
    Iceland = "111",
    Italy = "112",
    Jersey = "113",
    Jamaica = "114",
    Jordan = "115",
    Japan = "116",
    Kenya = "117",
    Kyrgyzstan = "118",
    Cambodia = "119",
    Kiribati = "120",
    Comoros = "121",
    SaintKitts = "122",
    NorthKorea = "123",
    SouthKorea = "124",
    Kuwait = "125",
    CaymanIslands = "126",
    Kazakhstan = "127",
    Laos = "128",
    Lebanon = "129",
    SaintLucia = "130",
    Liechtenstein = "131",
    SriLanka = "132",
    Liberia = "133",
    Lesotho = "134",
    Lithuania = "135",
    Luxembourg = "136",
    Latvia = "137",
    Libya = "138",
    Morocco = "139",
    Monaco = "140",
    Moldova = "141",
    Montenegro = "142",
    SaintMartin = "143",
    Madagascar = "144",
    MarshallIslands = "145",
    NorthMacedonia = "146",
    Mali = "147",
    Myanmar = "148",
    Mongolia = "149",
    Macao = "150",
    NorthernMarianaIslands = "151",
    Martinique = "152",
    Mauritania = "153",
    Montserrat = "154",
    Malta = "155",
    Mauritius = "156",
    Maldives = "157",
    Malawi = "158",
    Mexico = "159",
    Malaysia = "160",
    Mozambique = "161",
    Namibia = "162",
    NewCaledonia = "163",
    Niger = "164",
    NorfolkIsland = "165",
    Nigeria = "166",
    Nicaragua = "167",
    Netherlands = "168",
    Norway = "169",
    Nepal = "170",
    Nauru = "171",
    Niue = "172",
    NewZealand = "173",
    Oman = "174",
    Panama = "175",
    Peru = "176",
    FrenchPolynesia = "177",
    PapuaNewGuinea = "178",
    Philippines = "179",
    Pakistan = "180",
    Poland = "181",
    SaintPierre = "182",
    Pitcairn = "183",
    PuertoRico = "184",
    PalestinianTerritory = "185",
    Portugal = "186",
    Palau = "187",
    Paraguay = "188",
    Qatar = "189",
    Reunion = "190",
    Romania = "191",
    Serbia = "192",
    Russia = "193",
    Rwanda = "194",
    SaudiArabia = "195",
    SolomonIslands = "196",
    Seychelles = "197",
    Sudan = "198",
    Sweden = "199",
    Singapore = "200",
    SaintHelena = "201",
    Slovenia = "202",
    SvalbardJanMayen = "203",
    Slovakia = "204",
    SierraLeone = "205",
    SanMarino = "206",
    Senegal = "207",
    Somalia = "208",
    Suriname = "209",
    SouthSudan = "210",
    SaoTome = "211",
    ElSalvador = "212",
    SintMaarten = "213",
    Syria = "214",
    Eswatini = "215",
    TurksCaicosIslands = "216",
    Chad = "217",
    FrenchSouthernTerritories = "218",
    Togo = "219",
    Thailand = "220",
    Tajikistan = "221",
    Tokelau = "222",
    TimorLeste = "223",
    Turkmenistan = "224",
    Tunisia = "225",
    Tonga = "226",
    Turkey = "227",
    TrinidadTobago = "228",
    Tuvalu = "229",
    Taiwan = "230",
    Tanzania = "231",
    Ukraine = "232",
    Uganda = "233",
    UnitedStatesIslands = "234",
    UnitedStates = "235",
    Uruguay = "236",
    Uzbekistan = "237",
    Vatican = "238",
    SaintVincent = "239",
    Venezuela = "240",
    BritishVirginIslands = "241",
    VirginIslands = "242",
    Vietnam = "243",
    Vanuatu = "244",
    WallisFutuna = "245",
    Samoa = "246",
    Kosovo = "247",
    Yemen = "248",
    Mayotte = "249",
    SouthAfrica = "250",
    Zambia = "251",
    Zimbabwe = "252",
    }

export const CountryTypes = [
    {key: "0", label: "Not Selected"},
    {key: "3", label: "Afghanistan"},
    {key: "16", label: "Aland Islands"},
    {key: "6", label: "Albania"},
    {key: "64", label: "Algeria"},
    {key: "12", label: "American Samoa"},
    {key: "1", label: "Andorra"},
    {key: "9", label: "Angola"},
    {key: "5", label: "Anguilla"},
    {key: "10", label: "Antarctica"},
    {key: "4", label: "Antigua and Barbuda"},
    {key: "11", label: "Argentina"},
    {key: "7", label: "Armenia"},
    {key: "15", label: "Aruba"},
    {key: "14", label: "Australia"},
    {key: "13", label: "Austria"},
    {key: "17", label: "Azerbaijan"},
    {key: "33", label: "Bahamas"},
    {key: "24", label: "Bahrain"},
    {key: "20", label: "Bangladesh"},
    {key: "19", label: "Barbados"},
    {key: "37", label: "Belarus"},
    {key: "21", label: "Belgium"},
    {key: "38", label: "Belize"},
    {key: "26", label: "Benin"},
    {key: "28", label: "Bermuda"},
    {key: "34", label: "Bhutan"},
    {key: "30", label: "Bolivia"},
    {key: "31", label: "Bonaire, Saint Eustatius and Saba "},
    {key: "18", label: "Bosnia and Herzegovina"},
    {key: "36", label: "Botswana"},
    {key: "35", label: "Bouvet Island"},
    {key: "32", label: "Brazil"},
    {key: "108", label: "British Indian Ocean Territory"},
    {key: "241", label: "British Virgin Islands"},
    {key: "29", label: "Brunei"},
    {key: "23", label: "Bulgaria"},
    {key: "22", label: "Burkina Faso"},
    {key: "25", label: "Burundi"},
    {key: "54", label: "Cabo Verde"},
    {key: "119", label: "Cambodia"},
    {key: "48", label: "Cameroon"},
    {key: "39", label: "Canada"},
    {key: "126", label: "Cayman Islands"},
    {key: "42", label: "Central African Republic"},
    {key: "217", label: "Chad"},
    {key: "47", label: "Chile"},
    {key: "49", label: "China"},
    {key: "56", label: "Christmas Island"},
    {key: "40", label: "Cocos Islands"},
    {key: "50", label: "Colombia"},
    {key: "121", label: "Comoros"},
    {key: "46", label: "Cook Islands"},
    {key: "51", label: "Costa Rica"},
    {key: "100", label: "Croatia"},
    {key: "53", label: "Cuba"},
    {key: "55", label: "Curacao"},
    {key: "57", label: "Cyprus"},
    {key: "58", label: "Czechia"},
    {key: "41", label: "Democratic Republic of the Congo"},
    {key: "61", label: "Denmark"},
    {key: "60", label: "Djibouti"},
    {key: "62", label: "Dominica"},
    {key: "63", label: "Dominican Republic"},
    {key: "65", label: "Ecuador"},
    {key: "67", label: "Egypt"},
    {key: "212", label: "El Salvador"},
    {key: "90", label: "Equatorial Guinea"},
    {key: "69", label: "Eritrea"},
    {key: "66", label: "Estonia"},
    {key: "215", label: "Eswatini"},
    {key: "71", label: "Ethiopia"},
    {key: "74", label: "Falkland Islands"},
    {key: "76", label: "Faroe Islands"},
    {key: "73", label: "Fiji"},
    {key: "72", label: "Finland"},
    {key: "77", label: "France"},
    {key: "82", label: "French Guiana"},
    {key: "177", label: "French Polynesia"},
    {key: "218", label: "French Southern Territories"},
    {key: "78", label: "Gabon"},
    {key: "87", label: "Gambia"},
    {key: "81", label: "Georgia"},
    {key: "59", label: "Germany"},
    {key: "84", label: "Ghana"},
    {key: "85", label: "Gibraltar"},
    {key: "91", label: "Greece"},
    {key: "86", label: "Greenland"},
    {key: "80", label: "Grenada"},
    {key: "89", label: "Guadeloupe"},
    {key: "94", label: "Guam"},
    {key: "93", label: "Guatemala"},
    {key: "83", label: "Guernsey"},
    {key: "88", label: "Guinea"},
    {key: "95", label: "Guinea-Bissau"},
    {key: "96", label: "Guyana"},
    {key: "101", label: "Haiti"},
    {key: "98", label: "Heard Island and McDonald Islands"},
    {key: "99", label: "Honduras"},
    {key: "97", label: "Hong Kong"},
    {key: "102", label: "Hungary"},
    {key: "111", label: "Iceland"},
    {key: "107", label: "India"},
    {key: "103", label: "Indonesia"},
    {key: "110", label: "Iran"},
    {key: "109", label: "Iraq"},
    {key: "104", label: "Ireland"},
    {key: "106", label: "Isle of Man"},
    {key: "105", label: "Israel"},
    {key: "112", label: "Italy"},
    {key: "45", label: "Ivory Coast"},
    {key: "114", label: "Jamaica"},
    {key: "116", label: "Japan"},
    {key: "113", label: "Jersey"},
    {key: "115", label: "Jordan"},
    {key: "127", label: "Kazakhstan"},
    {key: "117", label: "Kenya"},
    {key: "120", label: "Kiribati"},
    {key: "247", label: "Kosovo"},
    {key: "125", label: "Kuwait"},
    {key: "118", label: "Kyrgyzstan"},
    {key: "128", label: "Laos"},
    {key: "137", label: "Latvia"},
    {key: "129", label: "Lebanon"},
    {key: "134", label: "Lesotho"},
    {key: "133", label: "Liberia"},
    {key: "138", label: "Libya"},
    {key: "131", label: "Liechtenstein"},
    {key: "135", label: "Lithuania"},
    {key: "136", label: "Luxembourg"},
    {key: "150", label: "Macao"},
    {key: "144", label: "Madagascar"},
    {key: "158", label: "Malawi"},
    {key: "160", label: "Malaysia"},
    {key: "157", label: "Maldives"},
    {key: "147", label: "Mali"},
    {key: "155", label: "Malta"},
    {key: "145", label: "Marshall Islands"},
    {key: "152", label: "Martinique"},
    {key: "153", label: "Mauritania"},
    {key: "156", label: "Mauritius"},
    {key: "249", label: "Mayotte"},
    {key: "159", label: "Mexico"},
    {key: "75", label: "Micronesia"},
    {key: "141", label: "Moldova"},
    {key: "140", label: "Monaco"},
    {key: "149", label: "Mongolia"},
    {key: "142", label: "Montenegro"},
    {key: "154", label: "Montserrat"},
    {key: "139", label: "Morocco"},
    {key: "161", label: "Mozambique"},
    {key: "148", label: "Myanmar"},
    {key: "162", label: "Namibia"},
    {key: "171", label: "Nauru"},
    {key: "170", label: "Nepal"},
    {key: "168", label: "Netherlands"},
    {key: "8", label: "Netherlands Antilles"},
    {key: "163", label: "New Caledonia"},
    {key: "173", label: "New Zealand"},
    {key: "167", label: "Nicaragua"},
    {key: "164", label: "Niger"},
    {key: "166", label: "Nigeria"},
    {key: "172", label: "Niue"},
    {key: "165", label: "Norfolk Island"},
    {key: "123", label: "North Korea"},
    {key: "146", label: "North Macedonia"},
    {key: "151", label: "Northern Mariana Islands"},
    {key: "169", label: "Norway"},
    {key: "174", label: "Oman"},
    {key: "180", label: "Pakistan"},
    {key: "187", label: "Palau"},
    {key: "185", label: "Palestinian Territory"},
    {key: "175", label: "Panama"},
    {key: "178", label: "Papua New Guinea"},
    {key: "188", label: "Paraguay"},
    {key: "176", label: "Peru"},
    {key: "179", label: "Philippines"},
    {key: "183", label: "Pitcairn"},
    {key: "181", label: "Poland"},
    {key: "186", label: "Portugal"},
    {key: "184", label: "Puerto Rico"},
    {key: "189", label: "Qatar"},
    {key: "43", label: "Republic of the Congo"},
    {key: "190", label: "Reunion"},
    {key: "191", label: "Romania"},
    {key: "193", label: "Russia"},
    {key: "194", label: "Rwanda"},
    {key: "27", label: "Saint Barthelemy"},
    {key: "201", label: "Saint Helena"},
    {key: "122", label: "Saint Kitts and Nevis"},
    {key: "130", label: "Saint Lucia"},
    {key: "143", label: "Saint Martin"},
    {key: "182", label: "Saint Pierre and Miquelon"},
    {key: "239", label: "Saint Vincent and the Grenadines"},
    {key: "246", label: "Samoa"},
    {key: "206", label: "San Marino"},
    {key: "211", label: "Sao Tome and Principe"},
    {key: "195", label: "Saudi Arabia"},
    {key: "207", label: "Senegal"},
    {key: "192", label: "Serbia"},
    {key: "52", label: "Serbia and Montenegro"},
    {key: "197", label: "Seychelles"},
    {key: "205", label: "Sierra Leone"},
    {key: "200", label: "Singapore"},
    {key: "213", label: "Sint Maarten"},
    {key: "204", label: "Slovakia"},
    {key: "202", label: "Slovenia"},
    {key: "196", label: "Solomon Islands"},
    {key: "208", label: "Somalia"},
    {key: "250", label: "South Africa"},
    {key: "92", label: "South Georgia and the South Sandwich Islands"},
    {key: "124", label: "South Korea"},
    {key: "210", label: "South Sudan"},
    {key: "70", label: "Spain"},
    {key: "132", label: "Sri Lanka"},
    {key: "198", label: "Sudan"},
    {key: "209", label: "Suriname"},
    {key: "203", label: "Svalbard and Jan Mayen"},
    {key: "199", label: "Sweden"},
    {key: "44", label: "Switzerland"},
    {key: "214", label: "Syria"},
    {key: "230", label: "Taiwan"},
    {key: "221", label: "Tajikistan"},
    {key: "231", label: "Tanzania"},
    {key: "220", label: "Thailand"},
    {key: "223", label: "Timor Leste"},
    {key: "219", label: "Togo"},
    {key: "222", label: "Tokelau"},
    {key: "226", label: "Tonga"},
    {key: "228", label: "Trinidad and Tobago"},
    {key: "225", label: "Tunisia"},
    {key: "227", label: "Turkey"},
    {key: "224", label: "Turkmenistan"},
    {key: "216", label: "Turks and Caicos Islands"},
    {key: "229", label: "Tuvalu"},
    {key: "242", label: "U.S. Virgin Islands"},
    {key: "233", label: "Uganda"},
    {key: "232", label: "Ukraine"},
    {key: "2", label: "United Arab Emirates"},
    {key: "79", label: "United Kingdom"},
    {key: "235", label: "United States"},
    {key: "234", label: "United States Minor Outlying Islands"},
    {key: "236", label: "Uruguay"},
    {key: "237", label: "Uzbekistan"},
    {key: "244", label: "Vanuatu"},
    {key: "238", label: "Vatican"},
    {key: "240", label: "Venezuela"},
    {key: "243", label: "Vietnam"},
    {key: "245", label: "Wallis and Futuna"},
    {key: "68", label: "Western Sahara"},
    {key: "248", label: "Yemen"},
    {key: "251", label: "Zambia"},
    {key: "252", label: "Zimbabwe"},
];
